### PR TITLE
Proposed solution for #55, only certain files benefit from gzipping.

### PR DESCRIPTION
**Pull request by bool-dev**
Tried to do this with a simple list, I think this should work for most use-cases.

### CODE REVIEW

**Comment by SunDwarf** [comment]
Tests are needed for the new code - if you could add them, that'd be great, otherwise I'll try and write some up tonight.

**Comment by bool-dev** [comment]
Yes, i wanted to add some, but since gzip flag was not tested, and i was in a rush, i thought no need to add for this as well!
I will add some or get back to you, if I can't in the next hour.

**Comment by bool-dev** [comment]
@SunDwarf so i tried, but can't figure out how to add the test/how to test it, please do it from your end. Sorry to put this on you.

**Comment by SunDwarf** [comment]
Fuck it we'll do it live

**Comment by bool-dev** [comment]
:smiley: I will try and add tests for `gzip` and `gzip_only_exts` over the weekend.

So just confirming, mock calls are the best way to test for calls within functions? (since all of that is happening with more calls within `_write_files`)

_(i don't write tests for my project currently, so un familiar with the best approaches)_

**Pull request merged**
